[package]
name = "slamprust"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3.1"
futures = "0.3.30"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.7", package = "gtk4" }
mpd = "0.1.0"
once_cell = "1.19.0"
time = "0.3.36"

[dependencies.adw]
package = "libadwaita"
version = "0.5"
features = ["v1_4"]
